### ISSUE TITLE
Hermes and Metro errors

### ISSUE THREAD

**Issue by MelihaDuman** [AndreOneti/expo-serialport#1]
I clone your project to see what happens but I keep getting this errors  

ERROR  Error: Cannot find native module 'ExpoSerialport', js engine: hermes
ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes 

Do you have any suggestions?
here is my package.json 
{
  "name": "library4",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.15",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-serial-port-api": "^1.4.0-rc.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

**Comment by AndreOneti** [comment]
Did you generate the development build?
